### ISSUE TITLE
AttributeError after installation

### ISSUE THREAD

**Issue by poratamit** [google/vulncode-db#102]
After following the installation instructions, entering the web page yields this error:

![Screenshot from 2021-03-30 02-55-06](https://user-images.githubusercontent.com/6429327/112971400-097cc280-9104-11eb-85ae-f1248c06941a.png)

I received this error on both Ubuntu 16.04.7 and Ubuntu 18.04.02

**Comment by bluec0re** [comment]
Hm, looks like this is related to a newer version of sqlalchemy, thought this was fixed by 07bc3a89f08a004deefc913fcfd1cec2e0ee47d2. Can you share the sqlalchemy version you're using?

Thanks!

**Comment by poratamit** [comment]
The version automatically downloaded to the Docker instance is 1.4.3:
![sqlalchemy](https://user-images.githubusercontent.com/6429327/112975161-2d420780-9108-11eb-8949-c98a9397d151.png)

**Comment by poratamit** [comment]
Here is the complete log:

I can see that 1.4.3 is installed during installation of requirements in vcs_requirements.txt

amitp@ubuntu:~/vulncode-db$ ./setup.sh 
[*] Ensuring all *.yaml configuration files are available.
[*] Checking for app.yaml existence.
	[+] Created.
[*] Checking for vcs_proxy.yaml existence.
	[+] Created.
[*] Ensuring SSL certificates for the VCS proxy exist.
Generating a 4096 bit RSA private key
........................................................................................................................................................++
.....................................++
writing new private key to 'key.pem'
-----
	[+] Created.
[*] Ensuring all third-party dependencies are satisfied.
	[+] Satisfied.
[*] Setting up all relevant docker containers.
[sudo] password for amitp: 
database uses an image, skipping
Building vcs-proxy
Sending build context to Docker daemon  39.42MB

Step 1/7 : FROM python:3.7
3.7: Pulling from library/python
8bf9c589d5f9: Pulling fs layer
4c70e46d8b5f: Pulling fs layer
ea848ad42f0d: Pulling fs layer
48fe137f8d26: Pulling fs layer
4b13f6ed9b0c: Pulling fs layer
ba85279f50e0: Pulling fs layer
afb48cd4d4c8: Pulling fs layer
764c0f545211: Pulling fs layer
f7cc69c80101: Pulling fs layer
48fe137f8d26: Waiting
4b13f6ed9b0c: Waiting
ba85279f50e0: Waiting
afb48cd4d4c8: Waiting
764c0f545211: Waiting
f7cc69c80101: Waiting
4c70e46d8b5f: Verifying Checksum
4c70e46d8b5f: Download complete
ea848ad42f0d: Verifying Checksum
ea848ad42f0d: Download complete
8bf9c589d5f9: Verifying Checksum
8bf9c589d5f9: Download complete
8bf9c589d5f9: Pull complete
48fe137f8d26: Verifying Checksum
48fe137f8d26: Download complete
4c70e46d8b5f: Pull complete
ea848ad42f0d: Pull complete
48fe137f8d26: Pull complete
ba85279f50e0: Verifying Checksum
ba85279f50e0: Download complete
764c0f545211: Verifying Checksum
764c0f545211: Download complete
f7cc69c80101: Verifying Checksum
f7cc69c80101: Download complete
afb48cd4d4c8: Verifying Checksum
afb48cd4d4c8: Download complete
4b13f6ed9b0c: Verifying Checksum
4b13f6ed9b0c: Download complete
4b13f6ed9b0c: Pull complete
ba85279f50e0: Pull complete
afb48cd4d4c8: Pull complete
764c0f545211: Pull complete
f7cc69c80101: Pull complete
Digest: sha256:0a2f2121ff7d017e873992ca23ab8516786913cc3cde8270a88051ab6379dd06
Status: Downloaded newer image for python:3.7
 ---> 9f71717f61f8
Step 2/7 : WORKDIR /app_setup
 ---> Running in a8779b994a53
Removing intermediate container a8779b994a53
 ---> d8890c295c48
Step 3/7 : COPY vcs_requirements.txt /app_setup/
 ---> a76f4eede523
Step 4/7 : RUN pip3 install -r vcs_requirements.txt
 ---> Running in 3f738bfa6fe9
Collecting dulwich<0.20,>=0.19
  Downloading dulwich-0.19.16-py3-none-any.whl (428 kB)
Collecting gitpython==2.1.11
  Downloading GitPython-2.1.11-py2.py3-none-any.whl (448 kB)
Collecting Flask>=1.1.2
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting PyGithub==1.40
  Downloading PyGithub-1.40.tar.gz (2.6 MB)
Collecting unidiff==0.5.5
  Downloading unidiff-0.5.5-py2.py3-none-any.whl (14 kB)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Collecting sqlakeyset==0.1.1559103842
  Downloading sqlakeyset-0.1.1559103842-py2.py3-none-any.whl (11 kB)
Collecting gitdb2>=2.0.0
  Downloading gitdb2-4.0.2-py3-none-any.whl (1.1 kB)
Collecting requests>=2.14.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyjwt
  Downloading PyJWT-2.0.1-py3-none-any.whl (15 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.3-cp37-cp37m-manylinux2014_x86_64.whl (1.5 MB)
Collecting urllib3>=1.24.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting gitdb>=4.0.1
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
Collecting smmap<5,>=3.0.1
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux2010_x86_64.whl (33 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting six>=1.5
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-1.0.0-cp37-cp37m-manylinux2010_x86_64.whl (160 kB)
Collecting importlib-metadata
  Downloading importlib_metadata-3.10.0-py3-none-any.whl (14 kB)
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Building wheels for collected packages: PyGithub
  Building wheel for PyGithub (setup.py): started
  Building wheel for PyGithub (setup.py): finished with status 'done'
  Created wheel for PyGithub: filename=PyGithub-1.40-py3-none-any.whl size=3184948 sha256=80b87fe57d9fd11ab58d252edbb2d84e26f139c18d447050d21bb8fa533c8324
  Stored in directory: /root/.cache/pip/wheels/44/7f/95/7a5552a146f7f43beff9b471a978c139611851d51429d7da8a
Successfully built PyGithub
Installing collected packages: zipp, typing-extensions, smmap, urllib3, six, MarkupSafe, importlib-metadata, idna, greenlet, gitdb, chardet, certifi, Werkzeug, sqlalchemy, requests, python-dateutil, pyjwt, Jinja2, itsdangerous, gitdb2, click, unidiff, sqlakeyset, pyyaml, PyGithub, gitpython, Flask, dulwich
Successfully installed Flask-1.1.2 Jinja2-2.11.3 MarkupSafe-1.1.1 PyGithub-1.40 Werkzeug-1.0.1 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 dulwich-0.19.16 gitdb-4.0.7 gitdb2-4.0.2 gitpython-2.1.11 greenlet-1.0.0 idna-2.10 importlib-metadata-3.10.0 itsdangerous-1.1.0 pyjwt-2.0.1 python-dateutil-2.8.1 pyyaml-5.4.1 requests-2.25.1 six-1.15.0 smmap-4.0.0 sqlakeyset-0.1.1559103842 sqlalchemy-1.4.3 typing-extensions-3.7.4.3 unidiff-0.5.5 urllib3-1.26.4 zipp-3.4.1
Removing intermediate container 3f738bfa6fe9
 ---> d16d20293234
Step 5/7 : WORKDIR /app
 ---> Running in a5cef1e1732d
Removing intermediate container a5cef1e1732d
 ---> 29758ecefe84
Step 6/7 : EXPOSE 8088/tcp
 ---> Running in 711cc3b117ea
Removing intermediate container 711cc3b117ea
 ---> 5cd03b80232e
Step 7/7 : CMD ["/usr/local/bin/python", "-m", "gce_vcs_proxy"]
 ---> Running in 59c02e35143a
Removing intermediate container 59c02e35143a
 ---> 5f04afeb58e2
Successfully built 5f04afeb58e2
Successfully tagged vcs-proxy:latest
Building frontend
Sending build context to Docker daemon  39.42MB

Step 1/10 : FROM python:3.7
 ---> 9f71717f61f8
Step 2/10 : WORKDIR /app_setup
 ---> Using cache
 ---> d8890c295c48
Step 3/10 : COPY requirements.txt /app_setup/
 ---> 3c1b840f158f
Step 4/10 : COPY vcs_requirements.txt /app_setup/
 ---> bff4cd073ff1
Step 5/10 : COPY dev_requirements.txt /app_setup/
 ---> 55b9e18d9280
Step 6/10 : RUN apt-get -y install default-libmysqlclient-dev
 ---> Running in 2a76967dccf4
Reading package lists...
Building dependency tree...
Reading state information...
default-libmysqlclient-dev is already the newest version (1.0.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 2a76967dccf4
 ---> 388df33aaf0a
Step 7/10 : RUN pip3 install -r /app_setup/requirements.txt
 ---> Running in 097ec56bbeb3
Collecting dulwich<0.20,>=0.19
  Downloading dulwich-0.19.16-py3-none-any.whl (428 kB)
Collecting gitpython==2.1.11
  Downloading GitPython-2.1.11-py2.py3-none-any.whl (448 kB)
Collecting Flask>=1.1.2
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting PyGithub==1.40
  Downloading PyGithub-1.40.tar.gz (2.6 MB)
Collecting unidiff==0.5.5
  Downloading unidiff-0.5.5-py2.py3-none-any.whl (14 kB)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Collecting sqlakeyset==0.1.1559103842
  Downloading sqlakeyset-0.1.1559103842-py2.py3-none-any.whl (11 kB)
Collecting mysqlclient>=1.4.6
  Downloading mysqlclient-2.0.3.tar.gz (88 kB)
Collecting Flask-Bootstrap==3.3.7.1
  Downloading Flask-Bootstrap-3.3.7.1.tar.gz (456 kB)
Collecting flask-marshmallow>=0.12.0
  Downloading flask_marshmallow-0.14.0-py2.py3-none-any.whl (10 kB)
Collecting Flask-Migrate>=2.2.1
  Downloading Flask_Migrate-2.7.0-py2.py3-none-any.whl (13 kB)
Collecting Authlib>=0.15.2
  Downloading Authlib-0.15.3-py2.py3-none-any.whl (203 kB)
Collecting Flask-Script>=2.0.6
  Downloading Flask-Script-2.0.6.tar.gz (43 kB)
Collecting Flask-SQLAlchemy>=2.4.0
  Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting Flask-WTF>=0.14.2
  Downloading Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting marshmallow-sqlalchemy>=0.23.1
  Downloading marshmallow_sqlalchemy-0.24.2-py2.py3-none-any.whl (18 kB)
Collecting google-auth==1.23
  Downloading google_auth-1.23.0-py2.py3-none-any.whl (114 kB)
Collecting flask-bouncer==0.3.0
  Downloading flask-bouncer-0.3.0.tar.gz (5.1 kB)
Collecting bouncer==0.1.12
  Downloading bouncer-0.1.12.tar.gz (5.5 kB)
Collecting flask-debugtoolbar>=0.10.1
  Downloading Flask_DebugToolbar-0.11.0-py2.py3-none-any.whl (325 kB)
Requirement already satisfied: setuptools>=40.6.3 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 21)) (54.2.0)
Collecting sqlparse==0.3.0
  Downloading sqlparse-0.3.0-py2.py3-none-any.whl (39 kB)
Collecting pygments==2.4.2
  Downloading Pygments-2.4.2-py2.py3-none-any.whl (883 kB)
Collecting colorama>=0.4.1
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting simplejson>=3.16.0
  Downloading simplejson-3.17.2-cp37-cp37m-manylinux2010_x86_64.whl (128 kB)
Collecting google-cloud-logging==2.0.0
  Downloading google_cloud_logging-2.0.0-py2.py3-none-any.whl (175 kB)
Collecting sqlalchemy<1.4
  Downloading SQLAlchemy-1.3.23-cp37-cp37m-manylinux2010_x86_64.whl (1.3 MB)
Collecting dominate
  Downloading dominate-2.6.0-py2.py3-none-any.whl (29 kB)
Collecting visitor
  Downloading visitor-0.1.3.tar.gz (3.3 kB)
Collecting blinker
  Downloading blinker-1.4.tar.gz (111 kB)
Collecting gitdb2>=2.0.0
  Downloading gitdb2-4.0.2-py3-none-any.whl (1.1 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting six>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.1-py3-none-any.whl (12 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting google-api-core[grpc]<2.0.0dev,>=1.22.0
  Downloading google_api_core-1.26.3-py2.py3-none-any.whl (93 kB)
Collecting google-cloud-core<2.0dev,>=1.4.1
  Downloading google_cloud_core-1.6.0-py2.py3-none-any.whl (28 kB)
Collecting proto-plus>=1.11.0
  Downloading proto_plus-1.18.1-py3-none-any.whl (42 kB)
Collecting requests>=2.14.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyjwt
  Downloading PyJWT-2.0.1-py3-none-any.whl (15 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cryptography
  Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
Collecting urllib3>=1.24.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting marshmallow>=2.0.0
  Downloading marshmallow-3.11.1-py2.py3-none-any.whl (46 kB)
Collecting alembic>=0.7
  Downloading alembic-1.5.8-py2.py3-none-any.whl (159 kB)
Collecting WTForms
  Downloading WTForms-2.3.3-py2.py3-none-any.whl (169 kB)
Collecting Mako
  Downloading Mako-1.1.4-py2.py3-none-any.whl (75 kB)
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting gitdb>=4.0.1
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
Collecting smmap<5,>=3.0.1
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Collecting packaging>=14.3
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
Collecting protobuf>=3.12.0
  Downloading protobuf-3.15.6-cp37-cp37m-manylinux1_x86_64.whl (1.0 MB)
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting grpcio<2.0dev,>=1.29.0
  Downloading grpcio-1.36.1-cp37-cp37m-manylinux2014_x86_64.whl (4.1 MB)
Collecting google-cloud-core<2.0dev,>=1.4.1
  Downloading google_cloud_core-1.5.0-py2.py3-none-any.whl (27 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux2010_x86_64.whl (33 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting cffi>=1.12
  Downloading cffi-1.14.5-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: bouncer, Flask-Bootstrap, flask-bouncer, PyGithub, Flask-Script, mysqlclient, blinker, visitor
  Building wheel for bouncer (setup.py): started
  Building wheel for bouncer (setup.py): finished with status 'done'
  Created wheel for bouncer: filename=bouncer-0.1.12-py3-none-any.whl size=4870 sha256=3787aca1bd2fe3b876e04b2f7558a5fba9ffaebece2fd0018fee58fc18393c45
  Stored in directory: /root/.cache/pip/wheels/b4/fd/4b/d93a9859e184e72fb49b9220e17a4e36786dc9dfc727352c0a
  Building wheel for Flask-Bootstrap (setup.py): started
  Building wheel for Flask-Bootstrap (setup.py): finished with status 'done'
  Created wheel for Flask-Bootstrap: filename=Flask_Bootstrap-3.3.7.1-py3-none-any.whl size=460123 sha256=4518efaad16bec6e4a462ec7f50e84baa4e5e10b9b42ae04a4f8dbffaa592e5d
  Stored in directory: /root/.cache/pip/wheels/67/a2/d6/50d039c9b59b4caca6d7b53839c8100354a52ab7553d2456eb
  Building wheel for flask-bouncer (setup.py): started
  Building wheel for flask-bouncer (setup.py): finished with status 'done'
  Created wheel for flask-bouncer: filename=flask_bouncer-0.3.0-py3-none-any.whl size=3391 sha256=91e4accc62393ffe897c92f5cd427881878a6628c48dababc35c8bc66e4bc98c
  Stored in directory: /root/.cache/pip/wheels/e3/00/83/f7896a16e7a58633444131f91c9b73995df7b5d9c76425bd51
  Building wheel for PyGithub (setup.py): started
  Building wheel for PyGithub (setup.py): finished with status 'done'
  Created wheel for PyGithub: filename=PyGithub-1.40-py3-none-any.whl size=3184948 sha256=380c8dfa1c39f0c1c5b1e5c4b39b57d400d552a38e406353715527ce379723fa
  Stored in directory: /root/.cache/pip/wheels/44/7f/95/7a5552a146f7f43beff9b471a978c139611851d51429d7da8a
  Building wheel for Flask-Script (setup.py): started
  Building wheel for Flask-Script (setup.py): finished with status 'done'
  Created wheel for Flask-Script: filename=Flask_Script-2.0.6-py3-none-any.whl size=14015 sha256=3037d7d02ee1fc1a85609bee98498dc0b227e8a917464e2fb322ed0867560f23
  Stored in directory: /root/.cache/pip/wheels/b5/fb/6b/01ea56e8a6486540ebe086676c8b3a823f1bbcc830df0cd4f0
  Building wheel for mysqlclient (setup.py): started
  Building wheel for mysqlclient (setup.py): finished with status 'done'
  Created wheel for mysqlclient: filename=mysqlclient-2.0.3-cp37-cp37m-linux_x86_64.whl size=114851 sha256=5aca73417673cbc9124b21dd71b11632ddb6b4b3aad690f223b6d15d183cca08
  Stored in directory: /root/.cache/pip/wheels/79/1c/f8/11fafab45fe6696eea63794a5d747b9c6b54990ac6f1885fb7
  Building wheel for blinker (setup.py): started
  Building wheel for blinker (setup.py): finished with status 'done'
  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13451 sha256=596c94f79bcb484d3e88aa93d314a69675b754399b3ae990c2f87779eb5c1317
  Stored in directory: /root/.cache/pip/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
  Building wheel for visitor (setup.py): started
  Building wheel for visitor (setup.py): finished with status 'done'
  Created wheel for visitor: filename=visitor-0.1.3-py3-none-any.whl size=3929 sha256=31d812836313f3710b9fcfef00c5c3a3785849e974374f32163e065b1145f775
  Stored in directory: /root/.cache/pip/wheels/64/34/11/053f47218984c9a31a00f911ed98dda036b867481dcc527a12
Successfully built bouncer Flask-Bootstrap flask-bouncer PyGithub Flask-Script mysqlclient blinker visitor
Installing collected packages: six, pyasn1, urllib3, rsa, pyparsing, pyasn1-modules, protobuf, MarkupSafe, idna, chardet, certifi, cachetools, Werkzeug, smmap, requests, pytz, pycparser, packaging, Jinja2, itsdangerous, googleapis-common-protos, google-auth, click, sqlalchemy, python-editor, python-dateutil, Mako, grpcio, google-api-core, gitdb, Flask, cffi, WTForms, visitor, pyjwt, proto-plus, marshmallow, google-cloud-core, gitdb2, Flask-SQLAlchemy, dominate, cryptography, bouncer, blinker, alembic, unidiff, sqlparse, sqlakeyset, simplejson, pyyaml, pygments, PyGithub, mysqlclient, marshmallow-sqlalchemy, google-cloud-logging, gitpython, Flask-WTF, Flask-Script, Flask-Migrate, flask-marshmallow, flask-debugtoolbar, flask-bouncer, Flask-Bootstrap, dulwich, colorama, Authlib
Successfully installed Authlib-0.15.3 Flask-1.1.2 Flask-Bootstrap-3.3.7.1 Flask-Migrate-2.7.0 Flask-SQLAlchemy-2.5.1 Flask-Script-2.0.6 Flask-WTF-0.14.3 Jinja2-2.11.3 Mako-1.1.4 MarkupSafe-1.1.1 PyGithub-1.40 WTForms-2.3.3 Werkzeug-1.0.1 alembic-1.5.8 blinker-1.4 bouncer-0.1.12 cachetools-4.2.1 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 click-7.1.2 colorama-0.4.4 cryptography-3.4.7 dominate-2.6.0 dulwich-0.19.16 flask-bouncer-0.3.0 flask-debugtoolbar-0.11.0 flask-marshmallow-0.14.0 gitdb-4.0.7 gitdb2-4.0.2 gitpython-2.1.11 google-api-core-1.26.3 google-auth-1.23.0 google-cloud-core-1.5.0 google-cloud-logging-2.0.0 googleapis-common-protos-1.53.0 grpcio-1.36.1 idna-2.10 itsdangerous-1.1.0 marshmallow-3.11.1 marshmallow-sqlalchemy-0.24.2 mysqlclient-2.0.3 packaging-20.9 proto-plus-1.18.1 protobuf-3.15.6 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pygments-2.4.2 pyjwt-2.0.1 pyparsing-2.4.7 python-dateutil-2.8.1 python-editor-1.0.4 pytz-2021.1 pyyaml-5.4.1 requests-2.25.1 rsa-4.7.2 simplejson-3.17.2 six-1.15.0 smmap-4.0.0 sqlakeyset-0.1.1559103842 sqlalchemy-1.3.23 sqlparse-0.3.0 unidiff-0.5.5 urllib3-1.26.4 visitor-0.1.3
Removing intermediate container 097ec56bbeb3
 ---> 87df40789dec
Step 8/10 : RUN pip3 install -r /app_setup/dev_requirements.txt
 ---> Running in 5a08fa33a8f0
Requirement already satisfied: dulwich<0.20,>=0.19 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 1)) (0.19.16)
Requirement already satisfied: gitpython==2.1.11 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 2)) (2.1.11)
Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 3)) (1.1.2)
Requirement already satisfied: PyGithub==1.40 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 4)) (1.40)
Requirement already satisfied: unidiff==0.5.5 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 5)) (0.5.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 6)) (5.4.1)
Requirement already satisfied: sqlakeyset==0.1.1559103842 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/vcs_requirements.txt (line 7)) (0.1.1559103842)
Requirement already satisfied: mysqlclient>=1.4.6 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 3)) (2.0.3)
Requirement already satisfied: Flask-Bootstrap==3.3.7.1 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 6)) (3.3.7.1)
Requirement already satisfied: flask-marshmallow>=0.12.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 7)) (0.14.0)
Requirement already satisfied: Flask-Migrate>=2.2.1 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 8)) (2.7.0)
Requirement already satisfied: Authlib>=0.15.2 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 9)) (0.15.3)
Requirement already satisfied: Flask-Script>=2.0.6 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 10)) (2.0.6)
Requirement already satisfied: Flask-SQLAlchemy>=2.4.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 11)) (2.5.1)
Requirement already satisfied: Flask-WTF>=0.14.2 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 14)) (0.14.3)
Requirement already satisfied: marshmallow-sqlalchemy>=0.23.1 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 15)) (0.24.2)
Requirement already satisfied: google-auth==1.23 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 16)) (1.23.0)
Requirement already satisfied: flask-bouncer==0.3.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 17)) (0.3.0)
Requirement already satisfied: bouncer==0.1.12 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 18)) (0.1.12)
Requirement already satisfied: flask-debugtoolbar>=0.10.1 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 20)) (0.11.0)
Requirement already satisfied: setuptools>=40.6.3 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 21)) (54.2.0)
Requirement already satisfied: sqlparse==0.3.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 22)) (0.3.0)
Requirement already satisfied: pygments==2.4.2 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 23)) (2.4.2)
Requirement already satisfied: colorama>=0.4.1 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 24)) (0.4.4)
Requirement already satisfied: simplejson>=3.16.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 28)) (3.17.2)
Requirement already satisfied: google-cloud-logging==2.0.0 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 33)) (2.0.0)
Requirement already satisfied: sqlalchemy<1.4 in /usr/local/lib/python3.7/site-packages (from -r /app_setup/requirements.txt (line 36)) (1.3.23)
Collecting pylint
  Downloading pylint-2.7.4-py3-none-any.whl (346 kB)
Collecting black>=20.8b1
  Downloading black-20.8b1.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pytest==5.2.0
  Downloading pytest-5.2.0-py3-none-any.whl (226 kB)
Collecting pytest-mock==1.11.0
  Downloading pytest_mock-1.11.0-py2.py3-none-any.whl (9.8 kB)
Collecting pytest-cov==2.7.1
  Downloading pytest_cov-2.7.1-py2.py3-none-any.whl (17 kB)
Collecting pytest-flask-sqlalchemy==1.0.2
  Downloading pytest_flask_sqlalchemy-1.0.2-py3-none-any.whl (11 kB)
Collecting bandit==1.6.2
  Downloading bandit-1.6.2-py2.py3-none-any.whl (122 kB)
Collecting mypy==0.770
  Downloading mypy-0.770-cp37-cp37m-manylinux1_x86_64.whl (21.7 MB)
Collecting mypy-extensions==0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting sqlalchemy-stubs==0.3
  Downloading sqlalchemy_stubs-0.3-py3-none-any.whl (115 kB)
Collecting pandas==0.25.1
  Downloading pandas-0.25.1-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
Collecting flask-shell-ipython==0.4.1
  Downloading flask_shell_ipython-0.4.1-py2.py3-none-any.whl (3.5 kB)
Collecting stevedore>=1.20.0
  Downloading stevedore-3.3.0-py3-none-any.whl (49 kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/site-packages (from bandit==1.6.2->-r /app_setup/dev_requirements.txt (line 10)) (1.15.0)
Requirement already satisfied: visitor in /usr/local/lib/python3.7/site-packages (from Flask-Bootstrap==3.3.7.1->-r /app_setup/requirements.txt (line 6)) (0.1.3)
Requirement already satisfied: dominate in /usr/local/lib/python3.7/site-packages (from Flask-Bootstrap==3.3.7.1->-r /app_setup/requirements.txt (line 6)) (2.6.0)
Requirement already satisfied: blinker in /usr/local/lib/python3.7/site-packages (from flask-bouncer==0.3.0->-r /app_setup/requirements.txt (line 17)) (1.4)
Collecting IPython>=5.0.0
  Downloading ipython-7.22.0-py3-none-any.whl (785 kB)
Requirement already satisfied: click in /usr/local/lib/python3.7/site-packages (from flask-shell-ipython==0.4.1->-r /app_setup/dev_requirements.txt (line 18)) (7.1.2)
Requirement already satisfied: gitdb2>=2.0.0 in /usr/local/lib/python3.7/site-packages (from gitpython==2.1.11->-r /app_setup/vcs_requirements.txt (line 2)) (4.0.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/site-packages (from google-auth==1.23->-r /app_setup/requirements.txt (line 16)) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from google-auth==1.23->-r /app_setup/requirements.txt (line 16)) (4.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/site-packages (from google-auth==1.23->-r /app_setup/requirements.txt (line 16)) (0.2.8)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in /usr/local/lib/python3.7/site-packages (from google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (1.5.0)
Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.22.0 in /usr/local/lib/python3.7/site-packages (from google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (1.26.3)
Requirement already satisfied: proto-plus>=1.11.0 in /usr/local/lib/python3.7/site-packages (from google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (1.18.1)
Collecting typed-ast<1.5.0,>=1.4.0
  Downloading typed_ast-1.4.2-cp37-cp37m-manylinux1_x86_64.whl (743 kB)
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from pandas==0.25.1->-r /app_setup/dev_requirements.txt (line 16)) (2021.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/site-packages (from pandas==0.25.1->-r /app_setup/dev_requirements.txt (line 16)) (2.8.1)
Collecting numpy>=1.13.3
  Downloading numpy-1.20.2-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.7/site-packages (from PyGithub==1.40->-r /app_setup/vcs_requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.7/site-packages (from PyGithub==1.40->-r /app_setup/vcs_requirements.txt (line 4)) (2.0.1)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.7.0-py3-none-any.whl (48 kB)
Collecting atomicwrites>=1.0
  Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/site-packages (from pytest==5.2.0->-r /app_setup/dev_requirements.txt (line 5)) (20.9)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.5.0
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting importlib-metadata>=0.12
  Downloading importlib_metadata-3.10.0-py3-none-any.whl (14 kB)
Collecting coverage>=4.4
  Downloading coverage-5.5-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.7/site-packages (from Authlib>=0.15.2->-r /app_setup/requirements.txt (line 9)) (3.4.7)
Collecting toml>=0.10.1
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting regex>=2020.1.8
  Downloading regex-2021.3.17-cp37-cp37m-manylinux2014_x86_64.whl (721 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python3.7/site-packages (from dulwich<0.20,>=0.19->-r /app_setup/vcs_requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/site-packages (from dulwich<0.20,>=0.19->-r /app_setup/vcs_requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.7/site-packages (from Flask>=1.1.2->-r /app_setup/vcs_requirements.txt (line 3)) (2.11.3)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.7/site-packages (from Flask>=1.1.2->-r /app_setup/vcs_requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.7/site-packages (from Flask>=1.1.2->-r /app_setup/vcs_requirements.txt (line 3)) (1.0.1)
Requirement already satisfied: marshmallow>=2.0.0 in /usr/local/lib/python3.7/site-packages (from flask-marshmallow>=0.12.0->-r /app_setup/requirements.txt (line 7)) (3.11.1)
Requirement already satisfied: alembic>=0.7 in /usr/local/lib/python3.7/site-packages (from Flask-Migrate>=2.2.1->-r /app_setup/requirements.txt (line 8)) (1.5.8)
Requirement already satisfied: WTForms in /usr/local/lib/python3.7/site-packages (from Flask-WTF>=0.14.2->-r /app_setup/requirements.txt (line 14)) (2.3.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.7/site-packages (from alembic>=0.7->Flask-Migrate>=2.2.1->-r /app_setup/requirements.txt (line 8)) (1.1.4)
Requirement already satisfied: python-editor>=0.3 in /usr/local/lib/python3.7/site-packages (from alembic>=0.7->Flask-Migrate>=2.2.1->-r /app_setup/requirements.txt (line 8)) (1.0.4)
Requirement already satisfied: gitdb>=4.0.1 in /usr/local/lib/python3.7/site-packages (from gitdb2>=2.0.0->gitpython==2.1.11->-r /app_setup/vcs_requirements.txt (line 2)) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in /usr/local/lib/python3.7/site-packages (from gitdb>=4.0.1->gitdb2>=2.0.0->gitpython==2.1.11->-r /app_setup/vcs_requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (1.53.0)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (3.15.6)
Requirement already satisfied: grpcio<2.0dev,>=1.29.0 in /usr/local/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-logging==2.0.0->-r /app_setup/requirements.txt (line 33)) (1.36.1)
Collecting zipp>=0.5
  Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pexpect>4.3
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting traitlets>=4.2
  Downloading traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting decorator
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting jedi>=0.16
  Downloading jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.18-py3-none-any.whl (367 kB)
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.1-py2.py3-none-any.whl (93 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.1.2->-r /app_setup/vcs_requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/site-packages (from packaging->pytest==5.2.0->-r /app_setup/dev_requirements.txt (line 5)) (2.4.7)
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth==1.23->-r /app_setup/requirements.txt (line 16)) (0.4.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub==1.40->-r /app_setup/vcs_requirements.txt (line 4)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub==1.40->-r /app_setup/vcs_requirements.txt (line 4)) (4.0.0)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.5.1-py2.py3-none-any.whl (106 kB)
Collecting ipython-genutils
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting mccabe<0.7,>=0.6
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting astroid<2.7,>=2.5.2
  Downloading astroid-2.5.2-py3-none-any.whl (222 kB)
Collecting isort<6,>=4.2.5
  Downloading isort-5.8.0-py3-none-any.whl (103 kB)
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy_object_proxy-1.6.0-cp37-cp37m-manylinux1_x86_64.whl (55 kB)
Collecting wrapt<1.13,>=1.11
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/site-packages (from cryptography->Authlib>=0.15.2->-r /app_setup/requirements.txt (line 9)) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.12->cryptography->Authlib>=0.15.2->-r /app_setup/requirements.txt (line 9)) (2.20)
Building wheels for collected packages: black, wrapt
  Building wheel for black (PEP 517): started
  Building wheel for black (PEP 517): finished with status 'done'
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl size=124184 sha256=fdb61508e4583fcbc21a656147ed7f12f152ce1518ed18fa963e738a7fb3189d
  Stored in directory: /root/.cache/pip/wheels/c5/85/79/f3af8daaf8037c0bf14beb3b7a1511a39b6e6902ca2aaf494e
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=76450 sha256=fd4934bf3f80bf3514a4dd1cba141e759214a70ab4a149767793fbd0cbda32b2
  Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Successfully built black wrapt
Installing collected packages: zipp, typing-extensions, importlib-metadata, wcwidth, py, ptyprocess, pluggy, parso, more-itertools, ipython-genutils, attrs, atomicwrites, wrapt, typed-ast, traitlets, pytest, prompt-toolkit, pickleshare, pexpect, pbr, mypy-extensions, lazy-object-proxy, jedi, decorator, backcall, toml, stevedore, regex, pytest-mock, pathspec, numpy, mypy, mccabe, isort, IPython, coverage, astroid, appdirs, sqlalchemy-stubs, pytest-flask-sqlalchemy, pytest-cov, pylint, pandas, flask-shell-ipython, black, bandit
Successfully installed IPython-7.22.0 appdirs-1.4.4 astroid-2.5.2 atomicwrites-1.4.0 attrs-20.3.0 backcall-0.2.0 bandit-1.6.2 black-20.8b1 coverage-5.5 decorator-4.4.2 flask-shell-ipython-0.4.1 importlib-metadata-3.10.0 ipython-genutils-0.2.0 isort-5.8.0 jedi-0.18.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 more-itertools-8.7.0 mypy-0.770 mypy-extensions-0.4.3 numpy-1.20.2 pandas-0.25.1 parso-0.8.1 pathspec-0.8.1 pbr-5.5.1 pexpect-4.8.0 pickleshare-0.7.5 pluggy-0.13.1 prompt-toolkit-3.0.18 ptyprocess-0.7.0 py-1.10.0 pylint-2.7.4 pytest-5.2.0 pytest-cov-2.7.1 pytest-flask-sqlalchemy-1.0.2 pytest-mock-1.11.0 regex-2021.3.17 sqlalchemy-stubs-0.3 stevedore-3.3.0 toml-0.10.2 traitlets-5.0.5 typed-ast-1.4.2 typing-extensions-3.7.4.3 wcwidth-0.2.5 wrapt-1.12.1 zipp-3.4.1
Removing intermediate container 5a08fa33a8f0
 ---> 183ab9d01f4c
Step 9/10 : WORKDIR /app
 ---> Running in 61b075e55449
Removing intermediate container 61b075e55449
 ---> a4091b909770
Step 10/10 : EXPOSE 8080/tcp
 ---> Running in ef2ca86099ae
Removing intermediate container ef2ca86099ae
 ---> 751cdc3429fc
Successfully built 751cdc3429fc
Successfully tagged frontend:latest
[*] You should be able to start everything with: ./docker/docker-admin.sh start
	[!] Please also run ./docker/docker-admin.sh to see general information on how to fill the database and more.

**Comment by bluec0re** [comment]
Ah thanks. Should be fixed with the newest commit. Can't test it right now though. Let me know if it still doesn't work.

**Comment by poratamit** [comment]
I reinstalled everything on a clean machine. I still get the same error, even though an older version is installed.
Here is the log:
[log2.txt](https://github.com/google/vulncode-db/files/6229068/log2.txt)

**Comment by bluec0re** [comment]
Sorry for the delay.  I was able to reproduce the error and it looks like this one was a result of a latest flask-sqlalchemy change (partially to make it compatible to sqlalchemy 1.4)
